# config/intrinsics.yaml

width: 320
height: 240

# calibration expects [fx, fy, cx, cy, k1, k2, p1, p2]
calibration:
  [
    476.71,        # fx  (from K[0,0])
    479.505,       # fy  (from K[1,1])
    350.738,       # cx  (from K[0,2])
    209.532,       # cy  (from K[1,2])
    -0.336591,     # k1
     0.159742,     # k2
     0.00012697,   # p1
    -0.0000722557  # p2
  ]